server {
    server_name mri.mindwaveja.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    root /var/www/melissa;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/mri.mindwaveja.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mri.mindwaveja.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name mri.mindwaveja.com;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}
